version: '3'
tasks:
  :build:
    cmds:
      - 'go build -o dist/main ./app/main.go'
    sources:
      - ./*.go,
      - ./**/*.go
      - ./**/*.tmpl

  :start:
    cmds:
      - task: :build
      - './dist/main'
    sources:
      - ./*.go,
      - ./**/*.go
      - ./**/*.tmpl
